import { connectDB } from "../db.js"
import bcrypt from "bcryptjs"

export default async function handler(req: any, res: any) {
  try {
    const db = await connectDB()
    const results: any = {}

    const employees = [
      {
        name: "John Smith",
        phone: "+1-555-0101",
        department: "Engineering",
        status: "active",
        email: "john.smith@company.com",
        salary: 85000,
        joinDate: "2023-01-15",
        joiningDate: "2023-01-15",
        role: "Senior Developer",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sarah Johnson",
        phone: "+1-555-0102",
        department: "Marketing",
        status: "active",
        email: "sarah.johnson@company.com",
        salary: 72000,
        joinDate: "2023-03-20",
        joiningDate: "2023-03-20",
        role: "Marketing Manager",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mike Chen",
        phone: "+1-555-0103",
        department: "Engineering",
        status: "active",
        email: "mike.chen@company.com",
        salary: 90000,
        joinDate: "2022-11-10",
        joiningDate: "2022-11-10",
        role: "Lead Engineer",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emily Davis",
        phone: "+1-555-0104",
        department: "HR",
        status: "active",
        email: "emily.davis@company.com",
        salary: 65000,
        joinDate: "2023-05-01",
        joiningDate: "2023-05-01",
        role: "HR Specialist",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Robert Wilson",
        phone: "+1-555-0105",
        department: "Finance",
        status: "on_leave",
        email: "robert.wilson@company.com",
        salary: 80000,
        joinDate: "2023-02-14",
        joiningDate: "2023-02-14",
        role: "Financial Analyst",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Lisa Anderson",
        phone: "+1-555-0106",
        department: "Engineering",
        status: "active",
        email: "lisa.anderson@company.com",
        salary: 88000,
        joinDate: "2023-04-03",
        joiningDate: "2023-04-03",
        role: "Frontend Developer",
        avatar: "/placeholder-user.jpg",
        password: await bcrypt.hash("password123", 10),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]

    await db.collection("users").deleteMany({})
    const empResult = await db.collection("users").insertMany(employees)
    results.employees = empResult.insertedIds.length

    const tasks = [
      {
        id: 1,
        title: "Complete Project Proposal",
        description: "Finalize and submit the Q2 project proposal to management",
        priority: "high",
        status: "inProgress",
        assignee: { name: "John Smith", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-15",
        tags: ["proposal", "important"],
      },
      {
        id: 2,
        title: "Client Presentation",
        description: "Prepare and deliver presentation to new client about our services",
        priority: "high",
        status: "todo",
        assignee: { name: "Sarah Johnson", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-15",
        tags: ["client", "presentation"],
      },
      {
        id: 3,
        title: "Update Documentation",
        description: "Update API documentation with new endpoints and parameters",
        priority: "medium",
        status: "todo",
        assignee: { name: "Mike Chen", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-16",
        tags: ["documentation"],
      },
      {
        id: 4,
        title: "Code Review",
        description: "Review pull requests from junior developers",
        priority: "high",
        status: "inProgress",
        assignee: { name: "Mike Chen", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-15",
        tags: ["code", "review"],
      },
      {
        id: 5,
        title: "Bug Fixes",
        description: "Fix critical bugs reported in the latest release",
        priority: "high",
        status: "inProgress",
        assignee: { name: "John Smith", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-16",
        tags: ["bugs", "critical"],
      },
      {
        id: 6,
        title: "Database Optimization",
        description: "Optimize slow queries in the user dashboard",
        priority: "medium",
        status: "todo",
        assignee: { name: "Mike Chen", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-17",
        tags: ["database", "performance"],
      },
      {
        id: 7,
        title: "Training Session",
        description: "Conduct training session on new development tools",
        priority: "low",
        status: "completed",
        assignee: { name: "Sarah Johnson", avatar: "/placeholder-user.jpg" },
        dueDate: "2024-01-14",
        tags: ["training"],
      },
    ]

    await db.collection("tasks").deleteMany({})
    const taskResult = await db.collection("tasks").insertMany(tasks)
    results.tasks = taskResult.insertedIds.length

    const projects = [
      {
        id: "proj-001",
        name: "Website Redesign",
        description: "Complete redesign of company website with modern UI/UX",
        progress: 75,
        status: "in_progress",
        priority: "high",
        deadline: "2024-02-28",
        team: ["/placeholder-user.jpg", "/placeholder-user.jpg", "/placeholder-user.jpg"],
        tasks: { total: 12, completed: 9 },
      },
      {
        id: "proj-002",
        name: "Mobile App Development",
        description: "Develop cross-platform mobile application for iOS and Android",
        progress: 45,
        status: "in_progress",
        priority: "high",
        deadline: "2024-04-15",
        team: ["/placeholder-user.jpg", "/placeholder-user.jpg"],
        tasks: { total: 20, completed: 9 },
      },
      {
        id: "proj-003",
        name: "API Integration",
        description: "Integrate third-party APIs for enhanced functionality",
        progress: 100,
        status: "completed",
        priority: "medium",
        deadline: "2024-01-10",
        team: ["/placeholder-user.jpg"],
        tasks: { total: 8, completed: 8 },
      },
      {
        id: "proj-004",
        name: "Database Migration",
        description: "Migrate legacy database to modern cloud infrastructure",
        progress: 60,
        status: "in_progress",
        priority: "high",
        deadline: "2024-03-30",
        team: ["/placeholder-user.jpg", "/placeholder-user.jpg", "/placeholder-user.jpg", "/placeholder-user.jpg"],
        tasks: { total: 15, completed: 9 },
      },
      {
        id: "proj-005",
        name: "Security Audit",
        description: "Comprehensive security audit and vulnerability assessment",
        progress: 30,
        status: "on_hold",
        priority: "medium",
        deadline: "2024-05-20",
        team: ["/placeholder-user.jpg"],
        tasks: { total: 10, completed: 3 },
      },
      {
        id: "proj-006",
        name: "Performance Optimization",
        description: "Optimize application performance and reduce load times",
        progress: 50,
        status: "in_progress",
        priority: "medium",
        deadline: "2024-02-15",
        team: ["/placeholder-user.jpg", "/placeholder-user.jpg"],
        tasks: { total: 14, completed: 7 },
      },
    ]

    await db.collection("projects").deleteMany({})
    const projResult = await db.collection("projects").insertMany(projects)
    results.projects = projResult.insertedIds.length

    const invoices = [
      {
        id: "INV-001",
        company: "Tech Solutions Inc",
        companyId: "comp-001",
        project: "Website Redesign",
        client: "ABC Corporation",
        amount: 500000,
        gstAmount: 90000,
        totalAmount: 590000,
        hasGST: true,
        gstPercentage: 18,
        status: "paid",
        dueDate: "Jan 15, 2024",
        issuedDate: "Dec 15, 2023",
        clientImage: "/placeholder-user.jpg",
      },
      {
        id: "INV-002",
        company: "Tech Solutions Inc",
        companyId: "comp-001",
        project: "Mobile App Development",
        client: "XYZ Enterprises",
        amount: 800000,
        gstAmount: 144000,
        totalAmount: 944000,
        hasGST: true,
        gstPercentage: 18,
        status: "pending",
        dueDate: "Jan 20, 2024",
        issuedDate: "Dec 20, 2023",
        clientImage: "/placeholder-user.jpg",
      },
      {
        id: "INV-003",
        company: "Digital Services Ltd",
        companyId: "comp-002",
        project: "API Integration",
        client: "Global Tech Co",
        amount: 350000,
        gstAmount: 63000,
        totalAmount: 413000,
        hasGST: true,
        gstPercentage: 18,
        status: "overdue",
        dueDate: "Dec 20, 2023",
        issuedDate: "Nov 20, 2023",
        clientImage: "/placeholder-user.jpg",
      },
      {
        id: "INV-004",
        company: "Digital Services Ltd",
        companyId: "comp-002",
        project: "Database Migration",
        client: "CloudBase Systems",
        amount: 600000,
        gstAmount: 108000,
        totalAmount: 708000,
        hasGST: true,
        gstPercentage: 18,
        status: "pending",
        dueDate: "Jan 25, 2024",
        issuedDate: "Dec 25, 2023",
        clientImage: "/placeholder-user.jpg",
      },
      {
        id: "INV-005",
        company: "Tech Solutions Inc",
        companyId: "comp-001",
        project: "Security Audit",
        client: "FinanceHub Inc",
        amount: 250000,
        gstAmount: 45000,
        totalAmount: 295000,
        hasGST: true,
        gstPercentage: 18,
        status: "paid",
        dueDate: "Jan 10, 2024",
        issuedDate: "Dec 10, 2023",
        clientImage: "/placeholder-user.jpg",
      },
      {
        id: "INV-006",
        company: "Digital Services Ltd",
        companyId: "comp-002",
        project: "Performance Optimization",
        client: "SpeedTech Co",
        amount: 400000,
        gstAmount: 72000,
        totalAmount: 472000,
        hasGST: true,
        gstPercentage: 18,
        status: "pending",
        dueDate: "Jan 30, 2024",
        issuedDate: "Dec 30, 2023",
        clientImage: "/placeholder-user.jpg",
      },
    ]

    await db.collection("invoices").deleteMany({})
    const invResult = await db.collection("invoices").insertMany(invoices)
    results.invoices = invResult.insertedIds.length

    res.json({
      message: "All collections seeded successfully with sample data",
      results,
    })
  } catch (error: any) {
    console.error("Error seeding:", error)
    res.status(500).json({ error: error.message })
  }
}
